[package]
name = "nerez"
version = "0.1.2"
edition = "2021"

[dependencies.bevy]
version = "0.8"
default-features = false
features = [
    "subpixel_glyph_atlas", "bevy_render", "bevy_ui",
    "bevy_core_pipeline", "bevy_asset",
    "wayland", "bevy_text", "bevy_sprite", "wav"
]

[dependencies]
rand = "0.8.5"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3