[package]
name = "nerez"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "0.6.0", features = ["subpixel_glyph_atlas"]}
rand = "0.8.4"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3